applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-dept/', 
    views.NewDepartamentoView.as_view(), 
    name='nuevo_departamento'
    ),
    path('listar-dept/', 
    views.DepartamentoListView.as_view(), 
    name='listar_departamento'),
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'empleado_app'

urlpatterns = [
    path('', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path('listar_all_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='all_empleados'
    ),
    path('listar_empleados_admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='admin_empleados'
    ),
    path('listar_por_area/<namearea>', 
        views.ListByArea.as_view(),
        name='lista_por_area'
    ),
    path('listar_por_clave/', views.ListEmpleadosKword.as_view()),
    path('listar_habilidades/', views.ListHabilidades.as_view()),
    path('listar_por_trabajo/<namejob>', views.ListByJob.as_view()),
    path('detalle-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
    ),
    path('crear-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='nuevo_empleado'
    ),
    path(
        'success/',
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'modificar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'borrar-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    )
]

project1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de las apps
    #re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.empleado.urls')),
    re_path('',include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'empleado_app:all_empleados' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:listar_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'empleado_app:admin_empleados' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href="{% url 'empleado_app:nuevo_empleado' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>