applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-dept/', 
    views.NewDepartamentoView.as_view(), 
    name='nuevo_departamento'
    ),
    path('listar-dept/', 
    views.DepartamentoListView.as_view(), 
    name='listar_departamento'),
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'empleado_app'

urlpatterns = [
    path('', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path('listar_all_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='all_empleados'
    ),
    path('listar_empleados_admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='admin_empleados'
    ),
    path('listar_por_area/<namearea>', 
        views.ListByArea.as_view(),
        name='lista_por_area'
    ),
    path('listar_por_clave/', views.ListEmpleadosKword.as_view()),
    path('listar_habilidades/', views.ListHabilidades.as_view()),
    path('listar_por_trabajo/<namejob>', views.ListByJob.as_view()),
    path('detalle-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
    ),
    path('crear-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='nuevo_empleado'
    ),
    path(
        'success/',
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'modificar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'borrar-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    )
]

project1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de las apps
    #re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.empleado.urls')),
    re_path('',include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default = False)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['name']
        unique_together = ('name','short_name')


    def __str__(self):
        return str(self.id) + '-' + self.name + ' - ' + self.short_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=60)
    short_name = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.empleado.models import Empleado
from .models import Departamento

# Create your views here.
class DepartamentoListView(ListView):
    template_name ="departamento/lista.html"
    model = Departamento
    context_object_name= 'departamentos'

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        depa =Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        depa.save()
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Departamentos
{% endblock title %}


{% block body %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for d in departamentos %}
                        <tr>
                            <td>{{d.name}}</td>
                            <td>{{d.short_name}}</td>
                            <td><a class="button warning" href="{% url 'empleado_app:lista_por_area' d.short_name %}">Ver Empleados</a></td>
                        </tr>
                        {% endfor %}
                            
                    </tbody>

                </table>
            </div>
        </div>
    </div>
    
{% endblock body %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar Departamento
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}    
<div class="grid-container">
    <div class="grix-x">
        <h1 class="cell">Registrar departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.apellido}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Area:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>:Departamento
                    {{form.short_name}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock body %}
    