applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'empleado_app'

urlpatterns = [
    path('', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path('listar_all_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='all_empleados'
    ),
    path('listar_empleados_admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='admin_empleados'
    ),
    path('listar_por_area/<namearea>', 
        views.ListByArea.as_view(),
        name='lista_por_area'
    ),
    path('listar_por_clave/', views.ListEmpleadosKword.as_view()),
    path('listar_habilidades/', views.ListHabilidades.as_view()),
    path('listar_por_trabajo/<namejob>', views.ListByJob.as_view()),
    path('detalle-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
    ),
    path('crear-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='nuevo_empleado'
    ),
    path(
        'success/',
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'modificar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'borrar-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    )
]

project1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de las apps
    #re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.empleado.urls')),
    re_path('',include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleado/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
            verbose_name = 'Habilidad'
            verbose_name_plural = 'Habilidades de empleado'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):
    """Modelo para tabla empleado"""
    JOB_CHOICES = (
        ('0','Contador'),
        ('1','Administrador'),
        ('2','Economista'),
        ('3','Otro')
    )
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellido', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=160, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    hoja_vida = RichTextField()
    #image = models.ImageField(, upload_to=None, height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['job']
        unique_together = ('first_name','last_name')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + ' ' + self.last_name

applications/empleado/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Empleado
from .form import EmpleadoForm

# Create your views here.

#inicio


class InicioView(TemplateView):
    template_name = "inicio.html"
    

# 1- Lista todos los empleados de la empresa
class ListAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista

class ListaEmpleadosAdmin(ListView):
    template_name = 'empleado/lista_admin.html'
    paginate_by = 7
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

# 2- Listar todos los empleados que pertenecen a un area de la empresa
class ListByArea(ListView):
    template_name = 'empleado/list_byarea.html'
    context_object_name = 'empleados'
    

    def get_queryset(self):
        area = self.kwargs['namearea']
        lista = Empleado.objects.filter(
        departamento__short_name=area
    )
        return lista


# 4- Listar los empleados por palabra clave
class ListEmpleadosKword(ListView):
    template_name = 'empleado/by_kword.html'
    context_object_name='empleados'

    def get_queryset(self):
        print('*****************')
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            first_name= palabra_clave
        )
        return lista

# 5- Listar habilidades de un empleado

class ListHabilidades(ListView):
    template_name ='empleado/lista_habilidades.html'
    context_object_name ='habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=2)
        return empleado.habilidades.all()
    
# 3- Listar empleados por trabajo
class ListByJob(ListView):
    template_name = 'empleado/list_byjob.html'
    context_object_name = 'empleados'
    

    def get_queryset(self):
        trabajo = self.kwargs['namejob']
        lista = Empleado.objects.filter(
        job=trabajo
    )
        return lista

# DetailView

class EmpleadoDetailView(DetailView):
    template_name = "empleado/detail_view.html"
    model = Empleado

    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context

# CreateView


class SuccessView(TemplateView):
    template_name = "empleado/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "empleado/crear_empleado.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleado_app:admin_empleados')
    
    def form_valid(self, form):
        empleado = form.save()
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

# UpdateView

class EmpleadoUpdateView(UpdateView):
    template_name = "empleado/modificar.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        ]
    success_url = reverse_lazy('empleado_app:admin_empleados')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        
        return super(EmpleadoUpdateView, self).form_valid(form)

# DeleteView


class EmpleadoDeleteView(DeleteView):
    template_name = "empleado/borrar.html"
    model = Empleado
    success_url = reverse_lazy('empleado_app:admin_empleados')



    

templates/empleado/borrar.html
{% extends 'base.html' %}


{% block title %}
Eliminar Empleado
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.last_name }}</h1>

        <form class="cell" method="POST">{% csrf_token %}

            <div class="callout alert">
                <h5>Confirma que desea eliminarlo?</h5>
                <button type="submit" class="button alert">Eliminar</button>
            </div>
        </form>
    </div>
</div>

{% endblock body %}

templates/empleado/by_kword.html
<h1>Lista de empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>
            {{e}}
        </li>
    {% endfor %}
        

</ul>

templates/empleado/crear_empleado.html
{% extends 'base.html' %}


{% block title %}
Registrar Empleado
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Registrar empleado</h1>

    <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="medium-6 cell">
        <label>Nombres:
          {{ form.first_name }}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellidos:
          {{ form.last_name }}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Trabajo:
          {{ form.job }}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Departamento:
          {{ form.departamento }}
        </label>
      </div>
      <div class="medium-12 cell">
        <label>Habilidades:
          {{ form.habilidades }}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Imagen:
          {{ form.avatar }}
        </label>
      </div>
      <div class="medium-12 cell">
        <button type="submit" class="button success">Registrar</button>
      </div>
    </form>
  </div>
</div>

{% endblock body %}

templates/empleado/detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Detalle {{ object.full_name }}
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>
            
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/20.jpg' %}">
            {% endif %}                
            
            <div class="card-section">
                <h4>{{empleado.first_name}} {{empleado.last_name}}</h4>
                <p>{{empleado.departamento.short_name}}</p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all %}
                      <li>{{h.habilidad}}</li>  
                    {% endfor %}
                        
                </ul>
            </div>
        </div>

    </div>
</div>

{% endblock body %}

<h1>Ver detalle de: {{titulo}}</h1>

{{empleado}}

<h3>Todos los datos</h3>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.job}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>

templates/empleado/list_all.html
{% extends 'base.html' %}


{% block body %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de todos los empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Ingrese empleado">
            </div>
            <div class="cell large-3">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">OPCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:detalle_empleado' e.id %}">Ver</a></td>
                  </tr>
                     {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
          
          {% if is_paginated %}
          <nav aria-label="Pagination">
            <ul class="pagination">
                {% if  page_obj.has_previous %}
                  <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                  </li>
                {% endif %}                 
                
                {% for pagina in paginator.page_range  %}
                  
                  {% ifequal pagina page_obj.number %} 
                  <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                  {% else %}
                  <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                  {% endifequal %}               
                  
                {% endfor %}

                {% if  page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
          </nav>            
          {% endif %}
        </div>
    </div>
</div>

{% endblock body %}

templates/empleado/list_byarea.html
{% extends 'base.html' %}


{% block title %}
Empleados por area
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Empleados por area:</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">OPCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'empleado_app:detalle_empleado' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>

{% endblock body %}

templates/empleado/list_byjob.html
<h1>Lista de empleados por trabajo</h1>

<ul>
    
    {% for e in object_list %}
        <li>
            {{e}}
        </li>      
        
    {% endfor %}
        
</ul>

templates/empleado/lista_admin.html
{% extends 'base.html' %}


{% block body %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de todos los empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">OPCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td>
                        <a class="button warning" href="{% url 'empleado_app:modificar_empleado' e.id %}">Editar</a>
                        <a class="button alert" href="{% url 'empleado_app:eliminar_empleado' e.id %}">Eliminar</a>
                    </td>
                  </tr>
                     {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
          
          {% if is_paginated %}
          <nav aria-label="Pagination">
            <ul class="pagination">
                {% if  page_obj.has_previous %}
                  <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                  </li>
                {% endif %}                 
                
                {% for pagina in paginator.page_range  %}
                  
                  {% ifequal pagina page_obj.number %} 
                  <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                  {% else %}
                  <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                  {% endifequal %}               
                  
                {% endfor %}

                {% if  page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
          </nav>            
          {% endif %}
        </div>
    </div>
</div>

{% endblock body %}

templates/empleado/lista_habilidades.html
<h1>Lista de habilidades</h1>

<ul>
    {% for h in habilidades %}
        <li>
            {{h}}
        </li>
    {% endfor %}
</ul>

    

templates/empleado/modificar.html
{% extends 'base.html' %}

{% block title %}
Modificar Empleado
{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}

<div class="grid-contqainer">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Actualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/empleado/success.html
<h1>Se ha registrado un empleado con éxito!</h1>